<?xml version="1.0" encoding="UTF-8"?>
<WebServiceRequestEntity>
   <description></description>
   <name>Get UserProfile</name>
   <tag></tag>
   <elementGuidId>4a6e81a2-0d44-4a93-9fec-35ea5c8b6c78</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <followRedirects>false</followRedirects>
   <httpBody></httpBody>
   <httpBodyContent></httpBodyContent>
   <httpBodyType></httpBodyType>
   <httpHeaderProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x-id-token</name>
      <type>Main</type>
      <value>eyJraWQiOiJJV2Y3c0tGVVoxQTdwUEc2VlwvVktlUDJPOG53Q0lPbTFudTZBaDc1UG55RT0iLCJhbGciOiJSUzI1NiJ9.eyJhdF9oYXNoIjoiYkphRXFaYWhGRXdYUmxOUjRfSDI1ZyIsInN1YiI6IjMxYjI2OGYxLWVjYTgtNGEwMi1hZTg2LWNkNDZhNTNhYmE4ZCIsImNvZ25pdG86Z3JvdXBzIjpbImFwLXNvdXRoLTFfY0IzU2ZRWWliX0dvb2dsZSJdLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwiaXNzIjoiaHR0cHM6XC9cL2NvZ25pdG8taWRwLmFwLXNvdXRoLTEuYW1hem9uYXdzLmNvbVwvYXAtc291dGgtMV9jQjNTZlFZaWIiLCJjb2duaXRvOnVzZXJuYW1lIjoiR29vZ2xlXzExMTA5Mjc4ODIyNDA4MDYzODk2NCIsImdpdmVuX25hbWUiOiJEZWVwYSIsIm5vbmNlIjoib2xZbEN4Z2pUcWxFNTZBQTg5R0I4cmhmMUoxMV9RdmNWSE56RzBEOGMzOER5MEVuTmtEeWNGcklOU0xOdWNSdlNuUHNEM0QxYXBnUWRybUxQeURKMWZtMFdxeWVtRDlBenpmTVpfZTVOYXptOC1tSklReFhLYVRlOWg4OWh2aUxhMFJoTnVKdHNkNUZfamFrUkczSi03SVV4c0luQlVQTEpnWW9WSDRvMnRJIiwicGljdHVyZSI6Imh0dHBzOlwvXC9saDMuZ29vZ2xldXNlcmNvbnRlbnQuY29tXC9hLVwvQU9oMTRHalNmVnZ0eEt2UmRqT3d2TlQ3dVdBS2Q3OW4tVUVqRG4ybmFKc3l6UT1zOTYtYyIsImF1ZCI6IjRnOGNrZmM4bGx0OHE3MHZtYmtnMGg3dTM4IiwiaWRlbnRpdGllcyI6W3sidXNlcklkIjoiMTExMDkyNzg4MjI0MDgwNjM4OTY0IiwicHJvdmlkZXJOYW1lIjoiR29vZ2xlIiwicHJvdmlkZXJUeXBlIjoiR29vZ2xlIiwiaXNzdWVyIjpudWxsLCJwcmltYXJ5IjoidHJ1ZSIsImRhdGVDcmVhdGVkIjoiMTU3ODQ2ODIyNDcyNyJ9XSwidG9rZW5fdXNlIjoiaWQiLCJhdXRoX3RpbWUiOjE1ODkxODg4MDQsIm5hbWUiOiJEZWVwYSBSIiwiZXhwIjoxNTg5MTkyNDA0LCJpYXQiOjE1ODkxODg4MDQsImZhbWlseV9uYW1lIjoiUiIsImVtYWlsIjoiZGVlcGEucmVkZHlAYnlqdXMuY29tIn0.ANMyAF1ESU_5TEc3LheK4vMGl0yCwg4_ACLp4H1p93Pf49nUkDL-pDWFSYZo_Aaq5jclbSrH8wynSEUFvcHiuWraL_KMhJ5YBzbOD2UDtyGf1Ba2NNYIwq4Q6QQoo20wRa7rPBiSXjHhfXFj7wkl2PFEn9e-3XU8XkmmL7QowN6e4XSvt2uo9WCqnOh3oGTrlDXwGliO0B1Pp1V61_-qIM553k1tCn5D5cHBi9ppyCGjC-DsqIhKX4Ig5OEsBWRNAru0edFo7VeRuf2GzbCzfijjhzRw1oyl-K_yqJHanq1mku-o2RX46hpC06Pcd0Fktk72EcqnhEWfaIEbYTud3w</value>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x-access-token</name>
      <type>Main</type>
      <value>eyJraWQiOiJRQVhFTXhEK2Q2WVZYV1JLQ1wvblpqYjVlS1l6ZUlRNnpHN2ZTWFptbGdsRT0iLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiIzMWIyNjhmMS1lY2E4LTRhMDItYWU4Ni1jZDQ2YTUzYWJhOGQiLCJjb2duaXRvOmdyb3VwcyI6WyJhcC1zb3V0aC0xX2NCM1NmUVlpYl9Hb29nbGUiXSwidG9rZW5fdXNlIjoiYWNjZXNzIiwic2NvcGUiOiJhd3MuY29nbml0by5zaWduaW4udXNlci5hZG1pbiBwaG9uZSBvcGVuaWQgcHJvZmlsZSBlbWFpbCIsImF1dGhfdGltZSI6MTU4OTE4ODgwNCwiaXNzIjoiaHR0cHM6XC9cL2NvZ25pdG8taWRwLmFwLXNvdXRoLTEuYW1hem9uYXdzLmNvbVwvYXAtc291dGgtMV9jQjNTZlFZaWIiLCJleHAiOjE1ODkxOTI0MDQsImlhdCI6MTU4OTE4ODgwNCwidmVyc2lvbiI6MiwianRpIjoiN2I1NzAwOGUtZjhlMy00OGUyLWEwZjMtOWFjZWYzNzhmNGUxIiwiY2xpZW50X2lkIjoiNGc4Y2tmYzhsbHQ4cTcwdm1ia2cwaDd1MzgiLCJ1c2VybmFtZSI6Ikdvb2dsZV8xMTEwOTI3ODgyMjQwODA2Mzg5NjQifQ.CpY7lHrWXF9YEqSdygeuPwwtKCgSb3ZWLigZsT62kGfDxk-Re2mte_yBWcjTW8Xwiz6MEKJjr8pJ32SOm4cCJ7L9O02Ky1o7PJY2EuE1IVHlCpB4a-H4d2MEF1EtHbUSHtyh1_5I0oAM2sUh0lz7V1Urd-5i-vuwOI77SGj3cd2Z2-GttBTYoHwSpNpIXqPtBxjWD8PvP_4kbpy6QczBSTqrMdVV8NbK1WJg6x_v4RRjwC0rRJxW1aD5ZTBIX_nmAOP6ZIPZpByL2l3eDPM819n6S9ICe9xNjuOQi-aBenL-yR1bymTv3I9CjSx6ZJztv7i8NJak0E9yYsoSOgDiQQ</value>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x-refresh-token</name>
      <type>Main</type>
      <value>eyJjdHkiOiJKV1QiLCJlbmMiOiJBMjU2R0NNIiwiYWxnIjoiUlNBLU9BRVAifQ.Cs08MG6eKvgJySHpjCetU5bQo-D3_HSLm2TdByy7orQfbySoea6hXN3CuiGChI6nTwXMQ6FhVpPnh8UsiHSdx-AYExWsXHWNPS_Kyr1loDKlTO6xudl08Pj78XxxzmxajaKnj0d_ZjDW5iz4rcZ0hGnAODumYrT4llM5mE3TUpY6D45mBhV6yLNSpgHMN70WKDDOuONOuFeXZzBHAXEDP5IDpRaWk9QlNUOxZxtZrtm_sYz2r1jWX4xEON-O5KPrI8eDRjIQ88CXWEYoaHwfiCcKhNgMIVREYYgy-hvuo7Q8-USaBdVzuE4vNkNLLUcPJNm79R2CqcsjNbalnqe1Cg.-No5sV4WK1JATSbp.pEnELtVJsUtNTvwdhgRZfaH5utaekHohOTKmOtNlKEa4fMflQEmPyHfCGuLsbXjQmQfJIqIlEr_RqTqzsYId5FUGferCI4YEEb0gmNjlyQi45P_nS0YgOa_eJAFIH05j5f-qjx8PEoPI_tYSDxoUO3LMbQZilnBqzC5H4xmH1ThsVWFKYIlxSyzT693UO2VpFeyLT-eUDQCqn4RUlJesaBZHyFpSNswx7jMKJqUHdaP2kg6kKnX8ST_c-4k2V_ubLWeKzOHuQnssd1Z5rfktO3scTYMX9JFM5R-oYbsNUtcQs1LKKTjpPjr0V8K4FuGn8CEmk__0WlB_41n9dUDz0TraXw3FLY12D18Q13RvDqtCZMe0eoy0ntI9tZm9F2Vdo5R3Vt2vrK8_GzWIJRFXkccXjQjItnwuazIdIMXYz_7wvZ55Z6AXV55XhdggDhCRE6Mw6ia9z8Yr2gaR4wTSUo64y8Uj8VenRLVIi1cKNGc1VqhFkxiEWd5EDSphPkrh4MZ_sSYC-3wIbhzXYo7sFXA0mXuZv8HUABdvf5rFfep567_HnTLfFcMQVZN2obLyS18BFUioRzvWHuvyJ2VuD902E5ZESGTH4bWwZXaMae22_uZo1lajDn5OF72Ge0uIXHI1yBcr7mddGgdQfqRpAbIK8J-x8SZFF8gcrTcDxwbU7LXBFHebA2a1KK92_-R9YHfuZBimQTWbabYpNBtmkuURGqXXkoe2_0KH1MHOsGg7wYWkDwgAw5n4yGOVz1QAFc-c9MJWEaRn5eW-JiqQa3Dds1a9YdYgX5r3kEkXiiMtMbW6U5_JH_P0XKMa-_ZfLkdSa2ZzI6mZh1G6R1v9aN5U7xQwaRefAXCMnMmFkz1RE5F_-Nx5tUOJqyOa4AuJjT_RVP2VWNqv30Hc1N05iVu8RKRfzQ_8ue6-gaNikeoKzNIrH7Pub2dzSVk4bysT89bl5s10sa3C4WCmW2wAojYkHGYNZLoCt_MvzaHUv5zQRvpPzNVyhFzJ9YFf_pTVF2lbm7hj4VgdpEWb-62XqilOFHFUZfd7joeLGus9ql92vl4u_BjvuamdcQQOaB2kSfaThkiT9y4TeBVDBZECDOycSpdrPzC5my_LNcleuqUfVshN__F7Bzjp7q2ktcZ4cnJMsB1OT1z4jBYUuCgTWWyE8sgx8-c9WboKmtxcwRWEhk7nVLKcV4P7uH2LI2ZpOpUjmwIUVBWzX7-XZ9kCj7uT8v4jo38eHB4SYj2UNc_3NcAVGzmueqOUFp9PUK2DIMGfbZhH0-UWrRDNDKdq_i8Ib10k.98UdgCcpQbZ25y94tfL4Iw</value>
   </httpHeaderProperties>
   <migratedVersion>5.4.1</migratedVersion>
   <restRequestMethod>GET</restRequestMethod>
   <restUrl>https://nucleus.byjusorders.com/nucleusapi/usermanagement/employee/getUserProfile</restUrl>
   <serviceType>RESTful</serviceType>
   <soapBody></soapBody>
   <soapHeader></soapHeader>
   <soapRequestMethod></soapRequestMethod>
   <soapServiceFunction></soapServiceFunction>
   <verificationScript>import static org.assertj.core.api.Assertions.*

import com.kms.katalon.core.testobject.RequestObject
import com.kms.katalon.core.testobject.ResponseObject
import com.kms.katalon.core.webservice.keyword.WSBuiltInKeywords as WS
import com.kms.katalon.core.webservice.verification.WSResponseManager

import groovy.json.JsonSlurper
import internal.GlobalVariable as GlobalVariable

RequestObject request = WSResponseManager.getInstance().getCurrentRequest()

ResponseObject response = WSResponseManager.getInstance().getCurrentResponse()
</verificationScript>
   <wsdlAddress></wsdlAddress>
</WebServiceRequestEntity>
